spring:
  application:
    name: loja-virtual
  profiles:
    active: dev

server:
  port: 8080

n8n:
  webhook:
    url: http://localhost:5678/webhook-test/pedido-recomendacao
    timeout-ms: 30000

cors:
  allowed-origins: http://localhost:5173
